server:
  port: 80


spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://database-1.cqwhokv1vicr.ap-northeast-2.rds.amazonaws.com:3306/THIRD_TEAM
    username: FEELGOOD
    password: RLQNSWHGDMA!
    hikari:
      minimum-idle: 2
      maximum-pool-size: 3
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
  servlet:
    multipart:
      location: \java-works\files
      max-file-size: 50MB
      max-request-size: 100MB
        
        
mybatis:
  type-aliases-package: today.whatdo.festival.vo
  mapper-locations: mapper/**/*.xml
  configuration.map-underscore-to-camel-case: true